#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 17
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  sym_bold_open = 1,
  sym_italic_open = 2,
  sym_strikethrough_open = 3,
  sym_underline_open = 4,
  sym_verbatim_open = 5,
  sym_inline_math_open = 6,
  sym_bold_close = 7,
  sym_italic_close = 8,
  sym_strikethrough_close = 9,
  sym_underline_close = 10,
  sym_verbatim_close = 11,
  sym_inline_math_close = 12,
  sym__space = 13,
  sym__blank_line = 14,
  sym_tag_end = 15,
  sym_word = 16,
  sym__ = 17,
  sym_document = 18,
  sym_paragraph = 19,
  sym_bold = 20,
  sym_italic = 21,
  sym_underline = 22,
  sym_strikethrough = 23,
  sym_verbatim = 24,
  sym_inline_math = 25,
  aux_sym_document_repeat1 = 26,
  aux_sym_paragraph_repeat1 = 27,
  aux_sym_bold_repeat1 = 28,
  aux_sym_italic_repeat1 = 29,
  aux_sym_underline_repeat1 = 30,
  aux_sym_strikethrough_repeat1 = 31,
  aux_sym_verbatim_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_bold_open] = "open",
  [sym_italic_open] = "open",
  [sym_strikethrough_open] = "open",
  [sym_underline_open] = "open",
  [sym_verbatim_open] = "open",
  [sym_inline_math_open] = "open",
  [sym_bold_close] = "close",
  [sym_italic_close] = "close",
  [sym_strikethrough_close] = "close",
  [sym_underline_close] = "close",
  [sym_verbatim_close] = "close",
  [sym_inline_math_close] = "close",
  [sym__space] = "_space",
  [sym__blank_line] = "_blank_line",
  [sym_tag_end] = "tag_end",
  [sym_word] = "word",
  [sym__] = "_",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_underline] = "underline",
  [sym_strikethrough] = "strikethrough",
  [sym_verbatim] = "verbatim",
  [sym_inline_math] = "inline_math",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_bold_repeat1] = "bold_repeat1",
  [aux_sym_italic_repeat1] = "italic_repeat1",
  [aux_sym_underline_repeat1] = "underline_repeat1",
  [aux_sym_strikethrough_repeat1] = "strikethrough_repeat1",
  [aux_sym_verbatim_repeat1] = "verbatim_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_bold_open] = sym_bold_open,
  [sym_italic_open] = sym_bold_open,
  [sym_strikethrough_open] = sym_bold_open,
  [sym_underline_open] = sym_bold_open,
  [sym_verbatim_open] = sym_bold_open,
  [sym_inline_math_open] = sym_bold_open,
  [sym_bold_close] = sym_bold_close,
  [sym_italic_close] = sym_bold_close,
  [sym_strikethrough_close] = sym_bold_close,
  [sym_underline_close] = sym_bold_close,
  [sym_verbatim_close] = sym_bold_close,
  [sym_inline_math_close] = sym_bold_close,
  [sym__space] = sym__space,
  [sym__blank_line] = sym__blank_line,
  [sym_tag_end] = sym_tag_end,
  [sym_word] = sym_word,
  [sym__] = sym__,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_underline] = sym_underline,
  [sym_strikethrough] = sym_strikethrough,
  [sym_verbatim] = sym_verbatim,
  [sym_inline_math] = sym_inline_math,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_bold_repeat1] = aux_sym_bold_repeat1,
  [aux_sym_italic_repeat1] = aux_sym_italic_repeat1,
  [aux_sym_underline_repeat1] = aux_sym_underline_repeat1,
  [aux_sym_strikethrough_repeat1] = aux_sym_strikethrough_repeat1,
  [aux_sym_verbatim_repeat1] = aux_sym_verbatim_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_bold_open] = {
    .visible = true,
    .named = false,
  },
  [sym_italic_open] = {
    .visible = true,
    .named = false,
  },
  [sym_strikethrough_open] = {
    .visible = true,
    .named = false,
  },
  [sym_underline_open] = {
    .visible = true,
    .named = false,
  },
  [sym_verbatim_open] = {
    .visible = true,
    .named = false,
  },
  [sym_inline_math_open] = {
    .visible = true,
    .named = false,
  },
  [sym_bold_close] = {
    .visible = true,
    .named = false,
  },
  [sym_italic_close] = {
    .visible = true,
    .named = false,
  },
  [sym_strikethrough_close] = {
    .visible = true,
    .named = false,
  },
  [sym_underline_close] = {
    .visible = true,
    .named = false,
  },
  [sym_verbatim_close] = {
    .visible = true,
    .named = false,
  },
  [sym_inline_math_close] = {
    .visible = true,
    .named = false,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym__] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_strikethrough] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_italic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_underline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_strikethrough_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_verbatim_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 9,
  [13] = 10,
  [14] = 6,
  [15] = 9,
  [16] = 8,
  [17] = 6,
  [18] = 10,
  [19] = 8,
  [20] = 20,
  [21] = 9,
  [22] = 22,
  [23] = 6,
  [24] = 24,
  [25] = 10,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 27,
  [30] = 30,
  [31] = 26,
  [32] = 28,
  [33] = 27,
  [34] = 30,
  [35] = 26,
  [36] = 28,
  [37] = 30,
  [38] = 30,
  [39] = 26,
  [40] = 27,
  [41] = 28,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 42,
  [49] = 42,
  [50] = 42,
  [51] = 43,
  [52] = 46,
  [53] = 46,
  [54] = 45,
  [55] = 44,
  [56] = 42,
  [57] = 43,
  [58] = 45,
  [59] = 46,
  [60] = 44,
  [61] = 45,
  [62] = 44,
  [63] = 43,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 64,
  [68] = 64,
  [69] = 69,
  [70] = 66,
  [71] = 64,
  [72] = 72,
  [73] = 72,
  [74] = 74,
  [75] = 72,
  [76] = 72,
  [77] = 72,
  [78] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      if (eof) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 5},
  [10] = {.lex_state = 0, .external_lex_state = 6},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 6},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 4},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 6},
  [19] = {.lex_state = 0, .external_lex_state = 4},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 7},
  [27] = {.lex_state = 0, .external_lex_state = 8},
  [28] = {.lex_state = 0, .external_lex_state = 9},
  [29] = {.lex_state = 0, .external_lex_state = 8},
  [30] = {.lex_state = 0, .external_lex_state = 10},
  [31] = {.lex_state = 0, .external_lex_state = 7},
  [32] = {.lex_state = 0, .external_lex_state = 9},
  [33] = {.lex_state = 0, .external_lex_state = 8},
  [34] = {.lex_state = 0, .external_lex_state = 10},
  [35] = {.lex_state = 0, .external_lex_state = 7},
  [36] = {.lex_state = 0, .external_lex_state = 9},
  [37] = {.lex_state = 0, .external_lex_state = 10},
  [38] = {.lex_state = 0, .external_lex_state = 10},
  [39] = {.lex_state = 0, .external_lex_state = 7},
  [40] = {.lex_state = 0, .external_lex_state = 8},
  [41] = {.lex_state = 0, .external_lex_state = 9},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 3},
  [49] = {.lex_state = 0, .external_lex_state = 6},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 4},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 6},
  [55] = {.lex_state = 0, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0, .external_lex_state = 5},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 0, .external_lex_state = 3},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 11},
  [65] = {.lex_state = 0, .external_lex_state = 11},
  [66] = {.lex_state = 0, .external_lex_state = 12},
  [67] = {.lex_state = 0, .external_lex_state = 11},
  [68] = {.lex_state = 0, .external_lex_state = 11},
  [69] = {.lex_state = 0, .external_lex_state = 12},
  [70] = {.lex_state = 0, .external_lex_state = 11},
  [71] = {.lex_state = 0, .external_lex_state = 11},
  [72] = {.lex_state = 0, .external_lex_state = 13},
  [73] = {.lex_state = 0, .external_lex_state = 13},
  [74] = {.lex_state = 0, .external_lex_state = 13},
  [75] = {.lex_state = 0, .external_lex_state = 13},
  [76] = {.lex_state = 0, .external_lex_state = 13},
  [77] = {.lex_state = 0, .external_lex_state = 13},
  [78] = {.lex_state = 0},
};

enum {
  ts_external_token_bold_open = 0,
  ts_external_token_italic_open = 1,
  ts_external_token_strikethrough_open = 2,
  ts_external_token_underline_open = 3,
  ts_external_token_verbatim_open = 4,
  ts_external_token_inline_math_open = 5,
  ts_external_token_bold_close = 6,
  ts_external_token_italic_close = 7,
  ts_external_token_strikethrough_close = 8,
  ts_external_token_underline_close = 9,
  ts_external_token_verbatim_close = 10,
  ts_external_token_inline_math_close = 11,
  ts_external_token__space = 12,
  ts_external_token__blank_line = 13,
  ts_external_token_tag_end = 14,
  ts_external_token_word = 15,
  ts_external_token__ = 16,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_bold_open] = sym_bold_open,
  [ts_external_token_italic_open] = sym_italic_open,
  [ts_external_token_strikethrough_open] = sym_strikethrough_open,
  [ts_external_token_underline_open] = sym_underline_open,
  [ts_external_token_verbatim_open] = sym_verbatim_open,
  [ts_external_token_inline_math_open] = sym_inline_math_open,
  [ts_external_token_bold_close] = sym_bold_close,
  [ts_external_token_italic_close] = sym_italic_close,
  [ts_external_token_strikethrough_close] = sym_strikethrough_close,
  [ts_external_token_underline_close] = sym_underline_close,
  [ts_external_token_verbatim_close] = sym_verbatim_close,
  [ts_external_token_inline_math_close] = sym_inline_math_close,
  [ts_external_token__space] = sym__space,
  [ts_external_token__blank_line] = sym__blank_line,
  [ts_external_token_tag_end] = sym_tag_end,
  [ts_external_token_word] = sym_word,
  [ts_external_token__] = sym__,
};

static const bool ts_external_scanner_states[14][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_inline_math_open] = true,
    [ts_external_token_bold_close] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_strikethrough_close] = true,
    [ts_external_token_underline_close] = true,
    [ts_external_token_verbatim_close] = true,
    [ts_external_token_inline_math_close] = true,
    [ts_external_token__space] = true,
    [ts_external_token__blank_line] = true,
    [ts_external_token_tag_end] = true,
    [ts_external_token_word] = true,
    [ts_external_token__] = true,
  },
  [2] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_inline_math_open] = true,
    [ts_external_token__blank_line] = true,
    [ts_external_token_word] = true,
  },
  [3] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_word] = true,
  },
  [4] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_underline_close] = true,
    [ts_external_token_word] = true,
  },
  [5] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_strikethrough_close] = true,
    [ts_external_token_word] = true,
  },
  [6] = {
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_bold_close] = true,
    [ts_external_token_word] = true,
  },
  [7] = {
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_word] = true,
  },
  [8] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_word] = true,
  },
  [9] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_word] = true,
  },
  [10] = {
    [ts_external_token_bold_open] = true,
    [ts_external_token_strikethrough_open] = true,
    [ts_external_token_underline_open] = true,
    [ts_external_token_verbatim_open] = true,
    [ts_external_token_word] = true,
  },
  [11] = {
    [ts_external_token_verbatim_close] = true,
    [ts_external_token_word] = true,
  },
  [12] = {
    [ts_external_token_inline_math_close] = true,
    [ts_external_token_word] = true,
  },
  [13] = {
    [ts_external_token_word] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_bold_open] = ACTIONS(1),
    [sym_italic_open] = ACTIONS(1),
    [sym_strikethrough_open] = ACTIONS(1),
    [sym_underline_open] = ACTIONS(1),
    [sym_verbatim_open] = ACTIONS(1),
    [sym_inline_math_open] = ACTIONS(1),
    [sym_bold_close] = ACTIONS(1),
    [sym_italic_close] = ACTIONS(1),
    [sym_strikethrough_close] = ACTIONS(1),
    [sym_underline_close] = ACTIONS(1),
    [sym_verbatim_close] = ACTIONS(1),
    [sym_inline_math_close] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym__blank_line] = ACTIONS(1),
    [sym_tag_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym__] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(78),
    [sym_paragraph] = STATE(3),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [sym_verbatim] = STATE(4),
    [sym_inline_math] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [sym_bold_open] = ACTIONS(3),
    [sym_italic_open] = ACTIONS(5),
    [sym_strikethrough_open] = ACTIONS(7),
    [sym_underline_open] = ACTIONS(9),
    [sym_verbatim_open] = ACTIONS(11),
    [sym_inline_math_open] = ACTIONS(13),
    [sym__blank_line] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [2] = {
    [sym_paragraph] = STATE(2),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [sym_verbatim] = STATE(4),
    [sym_inline_math] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_bold_open] = ACTIONS(21),
    [sym_italic_open] = ACTIONS(24),
    [sym_strikethrough_open] = ACTIONS(27),
    [sym_underline_open] = ACTIONS(30),
    [sym_verbatim_open] = ACTIONS(33),
    [sym_inline_math_open] = ACTIONS(36),
    [sym__blank_line] = ACTIONS(39),
    [sym_word] = ACTIONS(42),
  },
  [3] = {
    [sym_paragraph] = STATE(2),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_underline] = STATE(4),
    [sym_strikethrough] = STATE(4),
    [sym_verbatim] = STATE(4),
    [sym_inline_math] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_bold_open] = ACTIONS(3),
    [sym_italic_open] = ACTIONS(5),
    [sym_strikethrough_open] = ACTIONS(7),
    [sym_underline_open] = ACTIONS(9),
    [sym_verbatim_open] = ACTIONS(11),
    [sym_inline_math_open] = ACTIONS(13),
    [sym__blank_line] = ACTIONS(47),
    [sym_word] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_bold_open,
    ACTIONS(5), 1,
      sym_italic_open,
    ACTIONS(7), 1,
      sym_strikethrough_open,
    ACTIONS(9), 1,
      sym_underline_open,
    ACTIONS(11), 1,
      sym_verbatim_open,
    ACTIONS(13), 1,
      sym_inline_math_open,
    ACTIONS(51), 1,
      sym_word,
    ACTIONS(49), 2,
      sym__blank_line,
      ts_builtin_sym_end,
    STATE(5), 7,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      sym_inline_math,
      aux_sym_paragraph_repeat1,
  [35] = 9,
    ACTIONS(55), 1,
      sym_bold_open,
    ACTIONS(58), 1,
      sym_italic_open,
    ACTIONS(61), 1,
      sym_strikethrough_open,
    ACTIONS(64), 1,
      sym_underline_open,
    ACTIONS(67), 1,
      sym_verbatim_open,
    ACTIONS(70), 1,
      sym_inline_math_open,
    ACTIONS(73), 1,
      sym_word,
    ACTIONS(53), 2,
      sym__blank_line,
      ts_builtin_sym_end,
    STATE(5), 7,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      sym_inline_math,
      aux_sym_paragraph_repeat1,
  [70] = 7,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(84), 1,
      sym_italic_close,
    ACTIONS(86), 1,
      sym_word,
    STATE(22), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [96] = 7,
    ACTIONS(88), 1,
      sym_bold_open,
    ACTIONS(91), 1,
      sym_italic_open,
    ACTIONS(94), 1,
      sym_strikethrough_open,
    ACTIONS(97), 1,
      sym_verbatim_open,
    ACTIONS(100), 1,
      sym_underline_close,
    ACTIONS(102), 1,
      sym_word,
    STATE(7), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [122] = 7,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(113), 1,
      sym_underline_close,
    ACTIONS(115), 1,
      sym_word,
    STATE(7), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [148] = 7,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(125), 1,
      sym_strikethrough_close,
    ACTIONS(127), 1,
      sym_word,
    STATE(24), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [174] = 7,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(137), 1,
      sym_bold_close,
    ACTIONS(139), 1,
      sym_word,
    STATE(20), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [200] = 7,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(115), 1,
      sym_word,
    ACTIONS(141), 1,
      sym_underline_close,
    STATE(7), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [226] = 7,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(127), 1,
      sym_word,
    ACTIONS(143), 1,
      sym_strikethrough_close,
    STATE(24), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [252] = 7,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(139), 1,
      sym_word,
    ACTIONS(145), 1,
      sym_bold_close,
    STATE(20), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [278] = 7,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(86), 1,
      sym_word,
    ACTIONS(147), 1,
      sym_italic_close,
    STATE(22), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [304] = 7,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(127), 1,
      sym_word,
    ACTIONS(149), 1,
      sym_strikethrough_close,
    STATE(24), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [330] = 7,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(115), 1,
      sym_word,
    ACTIONS(151), 1,
      sym_underline_close,
    STATE(7), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [356] = 7,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(86), 1,
      sym_word,
    ACTIONS(153), 1,
      sym_italic_close,
    STATE(22), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [382] = 7,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(139), 1,
      sym_word,
    ACTIONS(155), 1,
      sym_bold_close,
    STATE(20), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [408] = 7,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(115), 1,
      sym_word,
    ACTIONS(157), 1,
      sym_underline_close,
    STATE(7), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [434] = 7,
    ACTIONS(159), 1,
      sym_italic_open,
    ACTIONS(162), 1,
      sym_strikethrough_open,
    ACTIONS(165), 1,
      sym_underline_open,
    ACTIONS(168), 1,
      sym_verbatim_open,
    ACTIONS(171), 1,
      sym_bold_close,
    ACTIONS(173), 1,
      sym_word,
    STATE(20), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [460] = 7,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(127), 1,
      sym_word,
    ACTIONS(176), 1,
      sym_strikethrough_close,
    STATE(24), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [486] = 7,
    ACTIONS(178), 1,
      sym_bold_open,
    ACTIONS(181), 1,
      sym_strikethrough_open,
    ACTIONS(184), 1,
      sym_underline_open,
    ACTIONS(187), 1,
      sym_verbatim_open,
    ACTIONS(190), 1,
      sym_italic_close,
    ACTIONS(192), 1,
      sym_word,
    STATE(22), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [512] = 7,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(86), 1,
      sym_word,
    ACTIONS(195), 1,
      sym_italic_close,
    STATE(22), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [538] = 7,
    ACTIONS(197), 1,
      sym_bold_open,
    ACTIONS(200), 1,
      sym_italic_open,
    ACTIONS(203), 1,
      sym_underline_open,
    ACTIONS(206), 1,
      sym_verbatim_open,
    ACTIONS(209), 1,
      sym_strikethrough_close,
    ACTIONS(211), 1,
      sym_word,
    STATE(24), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [564] = 7,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(139), 1,
      sym_word,
    ACTIONS(214), 1,
      sym_bold_close,
    STATE(20), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [590] = 6,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(216), 1,
      sym_word,
    STATE(13), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [613] = 6,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(218), 1,
      sym_word,
    STATE(21), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [636] = 6,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(220), 1,
      sym_word,
    STATE(8), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [659] = 6,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(222), 1,
      sym_word,
    STATE(15), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [682] = 6,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(224), 1,
      sym_word,
    STATE(6), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [705] = 6,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(226), 1,
      sym_word,
    STATE(10), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [728] = 6,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(228), 1,
      sym_word,
    STATE(11), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [751] = 6,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(230), 1,
      sym_word,
    STATE(12), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [774] = 6,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(232), 1,
      sym_word,
    STATE(17), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [797] = 6,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(234), 1,
      sym_word,
    STATE(18), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [820] = 6,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(236), 1,
      sym_word,
    STATE(19), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [843] = 6,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(238), 1,
      sym_word,
    STATE(14), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [866] = 6,
    ACTIONS(76), 1,
      sym_bold_open,
    ACTIONS(78), 1,
      sym_strikethrough_open,
    ACTIONS(80), 1,
      sym_underline_open,
    ACTIONS(82), 1,
      sym_verbatim_open,
    ACTIONS(240), 1,
      sym_word,
    STATE(23), 5,
      sym_bold,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_italic_repeat1,
  [889] = 6,
    ACTIONS(129), 1,
      sym_italic_open,
    ACTIONS(131), 1,
      sym_strikethrough_open,
    ACTIONS(133), 1,
      sym_underline_open,
    ACTIONS(135), 1,
      sym_verbatim_open,
    ACTIONS(242), 1,
      sym_word,
    STATE(25), 5,
      sym_italic,
      sym_underline,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_bold_repeat1,
  [912] = 6,
    ACTIONS(117), 1,
      sym_bold_open,
    ACTIONS(119), 1,
      sym_italic_open,
    ACTIONS(121), 1,
      sym_underline_open,
    ACTIONS(123), 1,
      sym_verbatim_open,
    ACTIONS(244), 1,
      sym_word,
    STATE(9), 5,
      sym_bold,
      sym_italic,
      sym_underline,
      sym_verbatim,
      aux_sym_strikethrough_repeat1,
  [935] = 6,
    ACTIONS(105), 1,
      sym_bold_open,
    ACTIONS(107), 1,
      sym_italic_open,
    ACTIONS(109), 1,
      sym_strikethrough_open,
    ACTIONS(111), 1,
      sym_verbatim_open,
    ACTIONS(246), 1,
      sym_word,
    STATE(16), 5,
      sym_bold,
      sym_italic,
      sym_strikethrough,
      sym_verbatim,
      aux_sym_underline_repeat1,
  [958] = 1,
    ACTIONS(248), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [970] = 1,
    ACTIONS(250), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [982] = 1,
    ACTIONS(252), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [994] = 1,
    ACTIONS(254), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [1006] = 1,
    ACTIONS(256), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [1018] = 1,
    ACTIONS(258), 9,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_inline_math_open,
      sym__blank_line,
      sym_word,
      ts_builtin_sym_end,
  [1030] = 1,
    ACTIONS(248), 6,
      sym_bold_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_italic_close,
      sym_word,
  [1039] = 1,
    ACTIONS(248), 6,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_bold_close,
      sym_word,
  [1048] = 1,
    ACTIONS(248), 6,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_verbatim_open,
      sym_underline_close,
      sym_word,
  [1057] = 1,
    ACTIONS(250), 6,
      sym_bold_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_italic_close,
      sym_word,
  [1066] = 1,
    ACTIONS(256), 6,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_verbatim_open,
      sym_underline_close,
      sym_word,
  [1075] = 1,
    ACTIONS(256), 6,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_bold_close,
      sym_word,
  [1084] = 1,
    ACTIONS(254), 6,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_bold_close,
      sym_word,
  [1093] = 1,
    ACTIONS(252), 6,
      sym_italic_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_bold_close,
      sym_word,
  [1102] = 1,
    ACTIONS(248), 6,
      sym_bold_open,
      sym_italic_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_strikethrough_close,
      sym_word,
  [1111] = 1,
    ACTIONS(250), 6,
      sym_bold_open,
      sym_italic_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_strikethrough_close,
      sym_word,
  [1120] = 1,
    ACTIONS(254), 6,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_verbatim_open,
      sym_underline_close,
      sym_word,
  [1129] = 1,
    ACTIONS(256), 6,
      sym_bold_open,
      sym_italic_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_strikethrough_close,
      sym_word,
  [1138] = 1,
    ACTIONS(252), 6,
      sym_bold_open,
      sym_italic_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_strikethrough_close,
      sym_word,
  [1147] = 1,
    ACTIONS(254), 6,
      sym_bold_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_italic_close,
      sym_word,
  [1156] = 1,
    ACTIONS(252), 6,
      sym_bold_open,
      sym_strikethrough_open,
      sym_underline_open,
      sym_verbatim_open,
      sym_italic_close,
      sym_word,
  [1165] = 1,
    ACTIONS(250), 6,
      sym_bold_open,
      sym_italic_open,
      sym_strikethrough_open,
      sym_verbatim_open,
      sym_underline_close,
      sym_word,
  [1174] = 3,
    ACTIONS(260), 1,
      sym_verbatim_close,
    ACTIONS(262), 1,
      sym_word,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1184] = 3,
    ACTIONS(262), 1,
      sym_word,
    ACTIONS(264), 1,
      sym_verbatim_close,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1194] = 3,
    ACTIONS(266), 1,
      sym_inline_math_close,
    ACTIONS(268), 1,
      sym_word,
    STATE(66), 1,
      aux_sym_verbatim_repeat1,
  [1204] = 3,
    ACTIONS(262), 1,
      sym_word,
    ACTIONS(271), 1,
      sym_verbatim_close,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1214] = 3,
    ACTIONS(262), 1,
      sym_word,
    ACTIONS(273), 1,
      sym_verbatim_close,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1224] = 3,
    ACTIONS(275), 1,
      sym_inline_math_close,
    ACTIONS(277), 1,
      sym_word,
    STATE(66), 1,
      aux_sym_verbatim_repeat1,
  [1234] = 3,
    ACTIONS(266), 1,
      sym_verbatim_close,
    ACTIONS(279), 1,
      sym_word,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1244] = 3,
    ACTIONS(262), 1,
      sym_word,
    ACTIONS(282), 1,
      sym_verbatim_close,
    STATE(70), 1,
      aux_sym_verbatim_repeat1,
  [1254] = 2,
    ACTIONS(284), 1,
      sym_word,
    STATE(68), 1,
      aux_sym_verbatim_repeat1,
  [1261] = 2,
    ACTIONS(286), 1,
      sym_word,
    STATE(71), 1,
      aux_sym_verbatim_repeat1,
  [1268] = 2,
    ACTIONS(288), 1,
      sym_word,
    STATE(69), 1,
      aux_sym_verbatim_repeat1,
  [1275] = 2,
    ACTIONS(290), 1,
      sym_word,
    STATE(67), 1,
      aux_sym_verbatim_repeat1,
  [1282] = 2,
    ACTIONS(292), 1,
      sym_word,
    STATE(65), 1,
      aux_sym_verbatim_repeat1,
  [1289] = 2,
    ACTIONS(294), 1,
      sym_word,
    STATE(64), 1,
      aux_sym_verbatim_repeat1,
  [1296] = 1,
    ACTIONS(296), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 35,
  [SMALL_STATE(6)] = 70,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 174,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 226,
  [SMALL_STATE(13)] = 252,
  [SMALL_STATE(14)] = 278,
  [SMALL_STATE(15)] = 304,
  [SMALL_STATE(16)] = 330,
  [SMALL_STATE(17)] = 356,
  [SMALL_STATE(18)] = 382,
  [SMALL_STATE(19)] = 408,
  [SMALL_STATE(20)] = 434,
  [SMALL_STATE(21)] = 460,
  [SMALL_STATE(22)] = 486,
  [SMALL_STATE(23)] = 512,
  [SMALL_STATE(24)] = 538,
  [SMALL_STATE(25)] = 564,
  [SMALL_STATE(26)] = 590,
  [SMALL_STATE(27)] = 613,
  [SMALL_STATE(28)] = 636,
  [SMALL_STATE(29)] = 659,
  [SMALL_STATE(30)] = 682,
  [SMALL_STATE(31)] = 705,
  [SMALL_STATE(32)] = 728,
  [SMALL_STATE(33)] = 751,
  [SMALL_STATE(34)] = 774,
  [SMALL_STATE(35)] = 797,
  [SMALL_STATE(36)] = 820,
  [SMALL_STATE(37)] = 843,
  [SMALL_STATE(38)] = 866,
  [SMALL_STATE(39)] = 889,
  [SMALL_STATE(40)] = 912,
  [SMALL_STATE(41)] = 935,
  [SMALL_STATE(42)] = 958,
  [SMALL_STATE(43)] = 970,
  [SMALL_STATE(44)] = 982,
  [SMALL_STATE(45)] = 994,
  [SMALL_STATE(46)] = 1006,
  [SMALL_STATE(47)] = 1018,
  [SMALL_STATE(48)] = 1030,
  [SMALL_STATE(49)] = 1039,
  [SMALL_STATE(50)] = 1048,
  [SMALL_STATE(51)] = 1057,
  [SMALL_STATE(52)] = 1066,
  [SMALL_STATE(53)] = 1075,
  [SMALL_STATE(54)] = 1084,
  [SMALL_STATE(55)] = 1093,
  [SMALL_STATE(56)] = 1102,
  [SMALL_STATE(57)] = 1111,
  [SMALL_STATE(58)] = 1120,
  [SMALL_STATE(59)] = 1129,
  [SMALL_STATE(60)] = 1138,
  [SMALL_STATE(61)] = 1147,
  [SMALL_STATE(62)] = 1156,
  [SMALL_STATE(63)] = 1165,
  [SMALL_STATE(64)] = 1174,
  [SMALL_STATE(65)] = 1184,
  [SMALL_STATE(66)] = 1194,
  [SMALL_STATE(67)] = 1204,
  [SMALL_STATE(68)] = 1214,
  [SMALL_STATE(69)] = 1224,
  [SMALL_STATE(70)] = 1234,
  [SMALL_STATE(71)] = 1244,
  [SMALL_STATE(72)] = 1254,
  [SMALL_STATE(73)] = 1261,
  [SMALL_STATE(74)] = 1268,
  [SMALL_STATE(75)] = 1275,
  [SMALL_STATE(76)] = 1282,
  [SMALL_STATE(77)] = 1289,
  [SMALL_STATE(78)] = 1296,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(26),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(37),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(41),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(72),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(74),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(26),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(37),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(29),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(41),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(72),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(74),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2), SHIFT_REPEAT(31),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2), SHIFT_REPEAT(30),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2), SHIFT_REPEAT(40),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2), SHIFT_REPEAT(77),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_underline_repeat1, 2), SHIFT_REPEAT(7),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(38),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(27),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(36),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(73),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bold_repeat1, 2), SHIFT_REPEAT(20),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(39),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(33),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(32),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(75),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_repeat1, 2), SHIFT_REPEAT(22),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2), SHIFT_REPEAT(35),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2), SHIFT_REPEAT(34),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2), SHIFT_REPEAT(28),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2), SHIFT_REPEAT(76),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strikethrough_repeat1, 2), SHIFT_REPEAT(24),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underline, 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strikethrough, 3),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_verbatim_repeat1, 2),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_verbatim_repeat1, 2), SHIFT_REPEAT(66),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_verbatim_repeat1, 2), SHIFT_REPEAT(70),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [296] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_note_external_scanner_create(void);
void tree_sitter_note_external_scanner_destroy(void *);
bool tree_sitter_note_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_note_external_scanner_serialize(void *, char *);
void tree_sitter_note_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_note_external_scanner_create,
      tree_sitter_note_external_scanner_destroy,
      tree_sitter_note_external_scanner_scan,
      tree_sitter_note_external_scanner_serialize,
      tree_sitter_note_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
